######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 20 19:12:37 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
