######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 7 18:46:02 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AnalyticAircraft.h DEM.h Dorade.h precision.h read_dorade.h
SOURCES += AnalyticAircraft.cpp DEM.cpp Dorade.cpp main.cpp
LIBS += -lgeotiff -ltiff -lgeographic
QT += xml
#CONFIG += debug
